### ISSUE TITLE
TypedAction README to docs inconsistency

### ISSUE THREAD

**Issue by justjhong** [palantir/redoodle#10]
In the README an action is created through a TypedAction definition with 
`const action = FlipTable({
  tableId: "2567f216-59b7-4bfe-b46f-909c6711fea4",
  face: "happy"
});`
However, in docs it is shown as
`const action = FlipTable.create({
  tableId: "2567f216-59b7-4bfe-b46f-909c6711fea4",
  face: "happy"
});`
I believe the README should be corrected to use `.create()`

**Comment by crazytoucan** [comment]
Docs should all be consistent now per https://github.com/palantir/redoodle/pull/38
