### ISSUE TITLE
TypedAction.create() deprecated in favor of defineAction()

### ISSUE THREAD

**Issue by crazytoucan** [palantir/redoodle#35]
As of Redoodle 2.5.0, the old `TypedAction.create()` is now deprecated in favor of its near-equivalent `defineAction()`. This change was done for a few reasons:

- Fewer closures required per action definition, which ultimately speeds up boot cost of action definitions considerably.
- Better tree-shaking in modern webpack toolchains

For consumers, the following migration guide should be helpful:

1. All usages of `TypedAction.define()` and `TypedAction.defineWithoutPayload()` should be migrated to `defineAction()`.
2. All usages of `FooTypedAction.create(...)` and `FooTypedAction.createWithMeta(...)` should be migrated to `FooDefinedAction(...)`.
3. All usages of `FooTypedAction.is(action)` should be migrated to `isType(action, FooDefinedAction.TYPE)`

Any issues encountered during migration can be filed here or as a separate ticket.

**Comment by rhysbrettbowen** [comment]
https://github.com/palantir/redoodle/blob/master/src/defineAction.ts#L49 Looking at this line - shouldn't it be `arguments === 2` ? as the metadata would be the second argument

**Comment by crazytoucan** [comment]
Good catch! Apologies for the issue -- https://github.com/palantir/redoodle/pull/52
