### ISSUE TITLE
StoreCreator type is not compatible with redux's

### ISSUE THREAD

**Issue by giladgray** [palantir/redoodle#4]
### Code

```ts
import { createStore, loggingMiddleware } from "redoodle";
import { applyMiddleware } from "redux";
import thunk from "redux-thunk";

createStore(reducer, INITIAL_STATE, applyMiddleware(thunk, loggingMiddleware()));
//                                  ^ ERROR: Argument of type 'GenericStoreEnhancer' is not
//                                  assignable to parameter of type 'StoreEnhancer | undefined'.
```

### Full error
```
'Argument of type 'GenericStoreEnhancer' is not assignable to parameter of type 'StoreEnhancer | undefined'.
  Type 'GenericStoreEnhancer' is not assignable to type 'StoreEnhancer'.
    Types of parameters 'next' and 'next' are incompatible.
      Types of parameters 'initialState' and 'preloadedState' are incompatible.
        Type 'S | undefined' is not assignable to type 'S'.
          Type 'undefined' is not assignable to type 'S'.'
```

### How to fix

Fixing is so easy!

https://github.com/palantir/redoodle/blob/master/src/StoreCreator.ts#L34 
should read `initialState: S | undefined`

**Comment by adidahiya** [comment]
But I think that's the point of the redoodle `StoreCreator` opinion, explained the comment -- you need to ensure that your `initialState` is defined. So L34 shouldn't change.

We could consider changing `StoreEnhancer` to declare its argument as `next: StoreCreator<S | undefined>` or to wrap & re-export `applyMiddleware` with a redoodle-compatible implementation.

**Comment by giladgray** [comment]
yes, upon further inspection the `StoreCreator` behavior is definitely intended and desirable. our initialState is definitely defined: the error comes from the third argument, not the second.

either way, changing _something_ to make the above code valid would be great.

**Comment by ralexand56** [comment]
What's the situation here? I'm still getting this error.

**Comment by crazytoucan** [comment]
Hey folks, now that Redoodle supplies its own `createStore()`, hopefully the small typing incompatibilities will go away. If you still do want to use Redoodle functions, some light casting may be necessary because of the behavioral incompatibilities described above.

If you are still getting issues, please do reopen this issue or file a new one. Thank you.
